FROM jenkinsxio/jenkins-base:0.1.128

RUN apt-get update && apt-get install -y \
  default-jdk

# Maven
ENV MAVEN_VERSION 3.5.3
RUN curl -Lf http://central.maven.org/maven2/org/apache/maven/apache-maven/$MAVEN_VERSION/apache-maven-$MAVEN_VERSION-bin.tar.gz | tar -C /opt -xzv
ENV M2_HOME /opt/apache-maven-$MAVEN_VERSION
ENV maven.home $M2_HOME
ENV M2 $M2_HOME/bin
ENV PATH $M2:$PATH
