FROM JENKINS_BASE_TAG

RUN \
  echo "deb http://packages.erlang-solutions.com/debian stretch contrib" >> /etc/apt/sources.list

RUN \
    apt-get update && \
    apt-get install --allow-unauthenticated --assume-yes esl-erlang elixir

