kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "serverless.name" . }}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
- apiGroups:
  - jenkins.io
  resources:
  - pipelineactivities
  verbs:
  - get
  - create
  - update
- apiGroups:
  - jenkins.io
  resources:
  - environments
  verbs:
  - list
  - get
  - update
